#!/usr/bin/env bash

# joyproj • by jayimist@github.com • joyproj jfile templates
# Change at your liking!

PROJECT="/home/jay/Projects/joyproj"
OLD_WD="$PWD"

if [ "$1" = "in-home-dir" ]; then
    cd ~/.joyproj

    echo "[jbuild]: Building joyproj in ~/.joyproj ..."

        cp -r "${PROJECT}/src/dev-files" .
        cp "${PROJECT}/src/joyproj.py" .

    echo "  Done"
    exit 0
fi

cd "$PROJECT"

echo "[jbuild]: Building joyproj in project's build directory ..."

rm -r ./build/joyproj/*
cp -r ./src/* ./build/joyproj

echo "  Done"
