#!/usr/bin/env bash

# joyproj • by jayimist@github.com • joyproj jfile templates
# Change at your liking!

SESSION="joyproj"
PROJECT="/home/jay/Projects/joyproj"
OLD_WD="$PWD"

cd "$PROJECT"

if tmux has-session -t "$SESSION" 2>/dev/null; then
    tmux attach-session -t "$SESSION"
    exit 0
fi

tmux new-session -d -s "$SESSION"

tmux send-keys -t "$SESSION:0.0" "nvim src/joyproj.py src/projects.json README.md jdev jbuild jrun" Enter
tmux split-window -h -t "$SESSION"
tmux attach-session -t "$SESSION"

cd "$OLD_WD"
