#!/usr/bin/env bash

# joyproj • by jayimist@github.com • joyproj jfile templates
# Change at your liking!

PROJECT="/home/jay/Projects/joyproj"

~/.python/bin/python3 "${PROJECT}/build/joyproj/joyproj.py" "$@"
