#!/usr/bin/env bash

# joyproj • by jayimist@github.com • joyproj dev-file templates
# Change at your liking!

SESSION="proj"
PROJECT="/path/to/proj"
OLD_WD="$PWD"

if [ "$1" = "in-home-dir" ]; then
    # stuff
fi

cd "$PROJECT"

echo "[jbuild]: Building proj in project's build directory ..."

rm -r ./build/proj/*
cp -r ./src/* ./build/proj

echo "  Done"
